import { Product } from "../types";

export const featuredProducts = [
  {
    id: "1",
    name: "Audífonos inalámbricos premium",
    price: 299900,
    originalPrice: 399900,
    image: "/audifonos-premium.jpg",
    rating: 4.8,
  },
  {
    id: "2",
    name: "Teclado mecánico retroiluminado",
    price: 249900,
    originalPrice: 329900,
    image: "/teclado-mecanico.jpg",
    rating: 4.6,
  },
  {
    id: "3",
    name: "Mouse gamer ergonómico",
    price: 159900,
    originalPrice: 219900,
    image: "/mouse-gamer.jpg",
    rating: 4.5,
  },
];

export const allProducts: Product[] = [
  {
    id: "1",
    name: "Audífonos inalámbricos premium",
    price: 299900,
    originalPrice: 399900,
    image: "/audifonos-premium.jpg",
    rating: 4.8,
    category: "Audio",
  },
  {
    id: "2",
    name: "Teclado mecánico retroiluminado",
    price: 249900,
    originalPrice: 329900,
    image: "/teclado-mecanico.jpg",
    rating: 4.6,
    category: "Periféricos",
  },
  {
    id: "3",
    name: "Mouse gamer ergonómico",
    price: 159900,
    originalPrice: 219900,
    image: "/mouse-gamer.jpg",
    rating: 4.5,
    category: "Periféricos",
  },
  {
    id: "4",
    name: "Parlante bluetooth portátil",
    price: 189900,
    originalPrice: 259900,
    image: "/parlante-portatil.png",
    rating: 4.7,
    category: "Audio",
  },
  {
    id: "5",
    name: "Monitor LED 24 pulgadas",
    price: 679900,
    originalPrice: 829900,
    image: "/monitor-24.png",
    rating: 4.4,
    category: "Monitores",
  },
  {
    id: "6",
    name: "Cámara web HD con micrófono",
    price: 199900,
    originalPrice: 249900,
    image: "/camara-web.png",
    rating: 4.3,
    category: "Accesorios",
  },
  {
    id: "7",
    name: "Disco duro externo 1TB",
    price: 279900,
    originalPrice: 349900,
    image: "/disco-duro-1tb.png",
    rating: 4.6,
    category: "Almacenamiento",
  },
  {
    id: "8",
    name: "Silla ergonómica de oficina",
    price: 899900,
    originalPrice: 1099900,
    image: "/silla-ergonomica.png",
    rating: 4.5,
    category: "Oficina",
  },
  {
    id: "9",
    name: "Batería portátil 20000mAh",
    price: 139900,
    originalPrice: 179900,
    image: "/bateria-portatil.png",
    rating: 4.7,
    category: "Accesorios",
  },
  {
    id: "10",
    name: "Smartwatch deportivo",
    price: 499900,
    originalPrice: 649900,
    image: "/smartwatch.png",
    rating: 4.6,
    category: "Wearables",
  },
];
