import { Product } from "../types";

export const featuredProducts = [
  {
    id: "1",
    name: "Audífonos inalámbricos premium",
    description:
      "Auriculares de alta fidelidad con cancelación de ruido y batería de larga duración. Diseño cómodo para uso prolongado.",
    price: 299900,
    originalPrice: 399900,
    image: "/audifonos-premium.jpg",
    rating: 4.8,
    reviewCount: 124,
    category: "Audio",
    inStock: true,
    stockQuantity: 35,
  },
  {
    id: "2",
    name: "Teclado mecánico retroiluminado",
    description:
      "Teclado mecánico con switches de alto rendimiento y retroiluminación RGB personalizable. Ideal para gamers y programadores.",
    price: 249900,
    originalPrice: 329900,
    image: "/teclado-mecanico.jpg",
    rating: 4.6,
    reviewCount: 98,
    category: "Periféricos",
    inStock: true,
    stockQuantity: 42,
  },
  {
    id: "3",
    name: "Mouse gamer ergonómico",
    description:
      "Mouse ergonómico con sensor óptico de alta precisión y botones programables. Diseñado para sesiones largas de juego.",
    price: 159900,
    originalPrice: 219900,
    image: "/mouse-gamer.jpg",
    rating: 4.5,
    reviewCount: 85,
    category: "Periféricos",
    inStock: true,
    stockQuantity: 60,
  },
];

export const allProducts: Product[] = [
  {
    id: "1",
    name: "Audífonos inalámbricos premium",
    description:
      "Auriculares de alta fidelidad con cancelación de ruido y batería de larga duración. Diseño cómodo para uso prolongado.",
    price: 299900,
    originalPrice: 399900,
    image: "/audifonos-premium.jpg",
    rating: 4.8,
    reviewCount: 124,
    category: "Audio",
    inStock: true,
    stockQuantity: 35,
  },
  {
    id: "2",
    name: "Teclado mecánico retroiluminado",
    description:
      "Teclado mecánico con switches de alto rendimiento y retroiluminación RGB personalizable. Ideal para gamers y programadores.",
    price: 249900,
    originalPrice: 329900,
    image: "/teclado-mecanico.jpg",
    rating: 4.6,
    reviewCount: 98,
    category: "Periféricos",
    inStock: true,
    stockQuantity: 42,
  },
  {
    id: "3",
    name: "Mouse gamer ergonómico",
    description:
      "Mouse ergonómico con sensor óptico de alta precisión y botones programables. Diseñado para sesiones largas de juego.",
    price: 159900,
    originalPrice: 219900,
    image: "/mouse-gamer.jpg",
    rating: 4.5,
    reviewCount: 85,
    category: "Periféricos",
    inStock: true,
    stockQuantity: 60,
  },
  {
    id: "4",
    name: "Parlante bluetooth portátil",
    description:
      "Altavoz compacto con sonido envolvente y conectividad Bluetooth 5.0. Resistente al agua y con hasta 12 horas de autonomía.",
    price: 189900,
    originalPrice: 259900,
    image: "/parlante-bluetooth.jpg",
    rating: 4.7,
    reviewCount: 112,
    category: "Audio",
    inStock: true,
    stockQuantity: 48,
  },
  {
    id: "5",
    name: "Monitor LED 24 pulgadas",
    description:
      "Monitor Full HD de 24'' con panel IPS, colores vibrantes y frecuencia de actualización de 75Hz. Perfecto para oficina y entretenimiento.",
    price: 679900,
    originalPrice: 829900,
    image: "/monitor-24.jpg",
    rating: 4.4,
    reviewCount: 76,
    category: "Monitores",
    inStock: true,
    stockQuantity: 27,
  },
  {
    id: "6",
    name: "Cámara web HD con micrófono",
    description:
      "Cámara web de alta definición con micrófono integrado y ajuste automático de luz. Ideal para videollamadas y streaming.",
    price: 199900,
    originalPrice: 249900,
    image: "/camara-web.jpg",
    rating: 4.3,
    reviewCount: 54,
    category: "Accesorios",
    inStock: true,
    stockQuantity: 73,
  },
  {
    id: "7",
    name: "Disco duro externo 1TB",
    description:
      "Disco duro externo portátil con 1TB de capacidad. Compatible con USB 3.0 para transferencias rápidas y seguras.",
    price: 279900,
    originalPrice: 349900,
    image: "/disco-duro.jpg",
    rating: 4.6,
    reviewCount: 91,
    category: "Almacenamiento",
    inStock: true,
    stockQuantity: 40,
  },
  {
    id: "8",
    name: "Silla ergonómica de oficina",
    description:
      "Silla ergonómica con soporte lumbar ajustable y materiales transpirables. Diseñada para comodidad durante largas jornadas.",
    price: 899900,
    originalPrice: 1099900,
    image: "/silla-ergonomica.jpg",
    rating: 4.5,
    reviewCount: 65,
    category: "Oficina",
    inStock: true,
    stockQuantity: 18,
  },
  {
    id: "9",
    name: "Batería portátil 20000mAh",
    description:
      "Power bank de gran capacidad con carga rápida y puertos múltiples. Ideal para viajes y uso diario.",
    price: 139900,
    originalPrice: 179900,
    image: "/bateria-portatil.jpg",
    rating: 4.7,
    reviewCount: 109,
    category: "Accesorios",
    inStock: true,
    stockQuantity: 90,
  },
  {
    id: "10",
    name: "Smartwatch deportivo",
    description:
      "Reloj inteligente con monitoreo de ritmo cardíaco, GPS y resistencia al agua. Compatible con iOS y Android.",
    price: 499900,
    originalPrice: 649900,
    image: "/smartwatch.jpg",
    rating: 4.6,
    reviewCount: 134,
    category: "Wearables",
    inStock: false,
    stockQuantity: 38,
  },
];
